### ISSUE TITLE
Publication / Promotion de la version 1.4

### ISSUE THREAD

**Issue by MaelREBOUX** [aitf-sig-topo/voies-adresses#10]
Tâches à faire avant / après la publication de la version 1.4 du format Base Adresse Locale :

### Le fichier de spécification
- [x] relire et valider définitivement le google docs
- [x] dériver et remettre en forme la version OpenDocument
- [x] Produire le PDF de diffusion
- [x] Mettre à jour https://aitf-sig-topo.github.io/voies-adresses/

### Promotion
- [x] courriels aux partenaires
- [x] annonce sur liste AITF
- [x] annonce sur e-communauté CNFPT
- [x] annonce sur OSMOSE
- [x] annonce sur Slack adresse
- [x] annonce sur Twitter

### Divers
- [x] Faire une PR sur https://github.com/etalab/schema-bal
- [x] Faire une issue sur https://github.com/BaseAdresseNationale/mes-adresses pour demander la fusion des 2 onglets "Voies" et "Toponymes" en un seul "Toponymes"

**Comment by MaelREBOUX** [comment]
https://aitf-sig-topo.github.io/voies-adresses/ est à jour donc le format 1.4 est officiellement disponible.

**Comment by MaelREBOUX** [comment]
https://e-communautes.cnfpt.fr/information-geographique/content/publication-du-format-bal-v14

https://adressedatagouvfr.slack.com/archives/C01A76XVCV8/p1695307143154709

https://osmose.numerique.gouv.fr/jcms/221366956_SocialTopic/fr/publication-du-format-bal-v1-4

https://groups.google.com/g/aitf-gt-sigtopo/c/dqwwiT0TObM

**Comment by MaelREBOUX** [comment]
https://twitter.com/aitf_sig_topo/status/1704871419673231651

**Comment by MaelREBOUX** [comment]
PR sur le schéma format BAL : https://github.com/etalab/schema-bal/pull/2

**Comment by MaelREBOUX** [comment]
Issues pour l'éditeur mes adresses : https://github.com/BaseAdresseNationale/mes-adresses/issues/838

**Comment by fred-V13** [comment]
> https://aitf-sig-topo.github.io/voies-adresses/ est à jour donc le format 1.4 est officiellement disponible.

Bonsoir Maël merci pour tout.

Une question cependant(deux en fait)  👍 

1-Identifiant de toponyme sera identique pour toutes les adresses (toutes les lignes) pour ce même toponyme (=une voie quoi)
(ça me parait une évidence mais bon)

2-Identifiant d'adresse sera identique pour toutes les adresses identiques:
j'ai par exemple une ligne / adresse 81 AV DE MARSEILLE en position bati 
ET Une autre ligne / adresse 81 AV DE MARSEILLE en position entrée

Même Identifiant d'adresse sur les deux lignes ?

Merci

**Comment by MaelREBOUX** [comment]
Le slack adresse me paraît un meilleur endroit pour répondre ;)

**Comment by fred-V13** [comment]
vais essayer d'y rentrer alors :-)
